import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className="bg-background text-foreground font-glash-grotesk antialiased min-h-[100dvh]"
      >
        {children}
      </body>
    </html>
  );
}
